name: Copilot Agent Setup

on:
  workflow_call:

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/devcontainers/python:3.11
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install system dependencies
      run: |
        apt-get update
        apt-get install -y \
          build-essential \
          curl \
          git \
          postgresql-client \
          redis-tools
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
        pip install pre-commit pytest pytest-cov black ruff mypy
    
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install frontend dependencies
      run: |
        if [ -f package.json ]; then npm ci; fi
    
    - name: Setup pre-commit
      run: |
        pre-commit install
        pre-commit autoupdate
    
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Copilot"
        git config --global user.email "copilot@github.com"
        git config --global push.default current
        git config --global push.autoSetupRemote true
    
    - name: Setup environment
      run: |
        echo "export PYTHONPATH=/workspace" >> ~/.bashrc
        echo "export NODE_ENV=development" >> ~/.bashrc
        
    - name: Verify setup
      run: |
        python --version
        node --version
        npm --version
        git --version
        make --version || true
        
    - name: Run linters
      run: |
        ruff check . || true
        black --check . || true
        if [ -f package.json ]; then npm run lint || true; fi
    
    - name: Run tests
      env:
        CI: true
      run: |
        if [ -d tests ]; then pytest tests/ -v || true; fi
        if [ -f package.json ]; then npm test || true; fi